// <auto-generated />
using System;
using Celestia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Celestia.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220608110012_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Celestia.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth0id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Oslo, Norway",
                            Auth0Id = "",
                            CreatedAt = new DateTime(2022, 6, 8, 11, 0, 12, 706, DateTimeKind.Utc).AddTicks(964),
                            Email = "",
                            Name = "Lillie"
                        });
                });

            modelBuilder.Entity("Celestia.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_companies_author_id");

                    b.ToTable("companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 46,
                            Address = "Gamle Bekkekroken 4, Tandvik, Congo",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 23, 33, 15, 959, DateTimeKind.Utc).AddTicks(957),
                            IconUrl = "https://loremflickr.com/320/240?lock=1506050147",
                            Name = "Rasmussen Gruppen",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=1767739788"
                        },
                        new
                        {
                            Id = 47,
                            Address = "Damtjernet 00, Smehavn, Gibraltar",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 5, 3, 53, 724, DateTimeKind.Utc).AddTicks(1136),
                            IconUrl = "https://loremflickr.com/320/240?lock=2025404561",
                            Name = "Glosli ASA",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=246220858"
                        },
                        new
                        {
                            Id = 48,
                            Address = "Øvre Granmyra 9, Stavstrand, Mozambique",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 16, 9, 15, 315, DateTimeKind.Utc).AddTicks(7541),
                            IconUrl = "https://loremflickr.com/320/240?lock=1691843900",
                            Name = "Løken - Carlsen",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=379666226"
                        },
                        new
                        {
                            Id = 49,
                            Address = "Bjørkekollen 3, Sandsjøen, Niue",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 18, 33, 13, 613, DateTimeKind.Utc).AddTicks(2491),
                            IconUrl = "https://loremflickr.com/320/240?lock=1985511758",
                            Name = "Arnesen, Ødegård and Evensen",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=1975082147"
                        },
                        new
                        {
                            Id = 50,
                            Address = "Håkons Vei 94, Utvik, Sweden",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 22, 59, 59, 313, DateTimeKind.Utc).AddTicks(3485),
                            IconUrl = "https://loremflickr.com/320/240?lock=1797938821",
                            Name = "Olstad - Andresen",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=1615437008"
                        },
                        new
                        {
                            Id = 51,
                            Address = "Auroras Vei 58, Loø, Peru",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 20, 27, 59, 850, DateTimeKind.Utc).AddTicks(7063),
                            IconUrl = "https://loremflickr.com/320/240?lock=1569197008",
                            Name = "Olstad - Strand",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=177441712"
                        },
                        new
                        {
                            Id = 52,
                            Address = "Østre Heggekollen 0, Staveid, Gabon",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 16, 24, 22, 960, DateTimeKind.Utc).AddTicks(6392),
                            IconUrl = "https://loremflickr.com/320/240?lock=452599889",
                            Name = "Bjørnstad - Østli",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=1138093590"
                        },
                        new
                        {
                            Id = 53,
                            Address = "Smogeliveien 84, Smefjord, Swaziland",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 1, 43, 37, 752, DateTimeKind.Utc).AddTicks(903),
                            IconUrl = "https://loremflickr.com/320/240?lock=487986900",
                            Name = "Johansen BA",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=888981035"
                        },
                        new
                        {
                            Id = 54,
                            Address = "Østre Bruekra 4, Lofjell, Tunisia",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 9, 2, 13, 746, DateTimeKind.Utc).AddTicks(1229),
                            IconUrl = "https://loremflickr.com/320/240?lock=529308714",
                            Name = "Fjeld ASA",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=1176846228"
                        },
                        new
                        {
                            Id = 55,
                            Address = "Nedre Elvekroken 74, Tandsund, Brunei Darussalam",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 17, 56, 45, 547, DateTimeKind.Utc).AddTicks(230),
                            IconUrl = "https://loremflickr.com/320/240?lock=113320056",
                            Name = "Bjørnstad og Sønner",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=1141867536"
                        },
                        new
                        {
                            Id = 56,
                            Address = "Pettersensvei 58, Innodden, Belarus",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 1, 44, 10, 859, DateTimeKind.Utc).AddTicks(2260),
                            IconUrl = "https://loremflickr.com/320/240?lock=1557596101",
                            Name = "Strand RFH",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=198860474"
                        },
                        new
                        {
                            Id = 57,
                            Address = "Elinesgate 19, Nordfjord, Wallis and Futuna",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 5, 17, 7, 3, DateTimeKind.Utc).AddTicks(8986),
                            IconUrl = "https://loremflickr.com/320/240?lock=287419148",
                            Name = "Jørgensen - Jacobsen",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=2114086709"
                        },
                        new
                        {
                            Id = 58,
                            Address = "Carlsens Vei 4, Smeberg, Cayman Islands",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 2, 48, 30, 280, DateTimeKind.Utc).AddTicks(151),
                            IconUrl = "https://loremflickr.com/320/240?lock=1907301586",
                            Name = "Christiansen og Sønner",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=967152272"
                        },
                        new
                        {
                            Id = 59,
                            Address = "Eiriks Gate 37, Lilleø, India",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 5, 58, 14, 142, DateTimeKind.Utc).AddTicks(1046),
                            IconUrl = "https://loremflickr.com/320/240?lock=967498825",
                            Name = "Moen ASA",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=1625026820"
                        },
                        new
                        {
                            Id = 60,
                            Address = "Kirkeroa 13, Sandfjell, Portugal",
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 15, 54, 40, 261, DateTimeKind.Utc).AddTicks(2161),
                            IconUrl = "https://loremflickr.com/320/240?lock=2063365430",
                            Name = "Aas - Dahl",
                            WebsiteUrl = "https://loremflickr.com/320/240?lock=1035523760"
                        });
                });

            modelBuilder.Entity("Celestia.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_contacts_author_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_contacts_company_id");

                    b.ToTable("contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 16,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 4, 38, 23, 814, DateTimeKind.Utc).AddTicks(5826),
                            Email = "Eline_Ryan@gmail.com",
                            Name = "Eline",
                            Phone = "79858685"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 12, 31, 51, 225, DateTimeKind.Utc).AddTicks(46),
                            Email = "Maria.Eriksen@yahoo.com",
                            Name = "Maria",
                            Phone = "96 89 21 41"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 16, 25, 58, 794, DateTimeKind.Utc).AddTicks(4002),
                            Email = "Elias_Carlsen@yahoo.com",
                            Name = "Elias",
                            Phone = "+47 34 82 53 44"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 16, 52, 5, 843, DateTimeKind.Utc).AddTicks(3101),
                            Email = "Malin67@yahoo.com",
                            Name = "Malin",
                            Phone = "+47 13 70 79 29"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 16, 53, 25, 420, DateTimeKind.Utc).AddTicks(4149),
                            Email = "Alexander.Moen0@yahoo.com",
                            Name = "Alexander",
                            Phone = "51 65 05 79"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 14, 12, 19, 6, DateTimeKind.Utc).AddTicks(534),
                            Email = "Hedda.Solheim27@gmail.com",
                            Name = "Hedda",
                            Phone = "361 93 001"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 12, 3, 23, 344, DateTimeKind.Utc).AddTicks(4021),
                            Email = "Sindre_Ryan@gmail.com",
                            Name = "Sindre",
                            Phone = "92441479"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 18, 38, 27, 457, DateTimeKind.Utc).AddTicks(4310),
                            Email = "Amalie.Roed33@yahoo.com",
                            Name = "Amalie",
                            Phone = "73 00 37 20"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 10, 28, 59, 32, DateTimeKind.Utc).AddTicks(1319),
                            Email = "Ida_Bjerke11@yahoo.com",
                            Name = "Ida",
                            Phone = "40374553"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 6, 29, 32, 167, DateTimeKind.Utc).AddTicks(1151),
                            Email = "Lucas79@yahoo.com",
                            Name = "Lucas",
                            Phone = "052 48 675"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 3, 48, 29, 906, DateTimeKind.Utc).AddTicks(674),
                            Email = "Emilie.Johansen@yahoo.com",
                            Name = "Emilie",
                            Phone = "+47 57 10 95 97"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 7, 21, 48, 10, 850, DateTimeKind.Utc).AddTicks(2730),
                            Email = "Mathilde38@hotmail.com",
                            Name = "Mathilde",
                            Phone = "92 71 17 54"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 8, 52, 31, 615, DateTimeKind.Utc).AddTicks(7564),
                            Email = "Synne_Kristensen79@gmail.com",
                            Name = "Synne",
                            Phone = "+47 73 87 62 86"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 3, 52, 26, 343, DateTimeKind.Utc).AddTicks(9037),
                            Email = "Johannes.Torgersen@yahoo.com",
                            Name = "Johannes",
                            Phone = "994 13 486"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 6, 8, 2, 38, 8, 804, DateTimeKind.Utc).AddTicks(8210),
                            Email = "Elise.Olsen44@yahoo.com",
                            Name = "Elise",
                            Phone = "51 70 88 49"
                        });
                });

            modelBuilder.Entity("Celestia.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_folders");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_folders_author_id");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Celestia.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("FolderId")
                        .HasColumnType("integer")
                        .HasColumnName("folder_id");

                    b.Property<string>("PostingUrl")
                        .HasColumnType("text")
                        .HasColumnName("posting_url");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_jobs_author_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_jobs_company_id");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_jobs_folder_id");

                    b.ToTable("jobs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 61,
                            Address = "Bekkemyra 70, Vesthavn, Taiwan",
                            AuthorId = 1,
                            CompanyId = 49,
                            CreatedAt = new DateTime(2022, 6, 7, 17, 29, 20, 487, DateTimeKind.Utc).AddTicks(9920),
                            Deadline = new DateTime(2022, 6, 11, 6, 36, 42, 404, DateTimeKind.Utc).AddTicks(3722),
                            Description = "Perferendis et dolorem. In eum nemo aut. Cumque et totam sint adipisci. Perspiciatis voluptatem a repellat et ad. Sit quia illum quam tempora sit adipisci nam molestiae voluptatem. Magni nulla fugiat rerum ea.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=411957554",
                            Status = 1,
                            Title = "Architecto nihil tenetur."
                        },
                        new
                        {
                            Id = 62,
                            Address = "Martesgate 41, Smehelle, Russian Federation",
                            AuthorId = 1,
                            CompanyId = 51,
                            CreatedAt = new DateTime(2022, 6, 7, 21, 19, 37, 857, DateTimeKind.Utc).AddTicks(856),
                            Deadline = new DateTime(2022, 6, 14, 17, 50, 29, 429, DateTimeKind.Utc).AddTicks(2497),
                            Description = "Reiciendis minima voluptatem tenetur laudantium occaecati labore molestiae nulla. Ex eos incidunt ipsam deserunt quasi sint. Rerum sunt quasi omnis. Libero possimus vel nihil ipsum.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1903067041",
                            Status = 1,
                            Title = "Deserunt est fugit."
                        },
                        new
                        {
                            Id = 63,
                            Address = "Furugata 2, Tandsund, Mexico",
                            AuthorId = 1,
                            CompanyId = 47,
                            CreatedAt = new DateTime(2022, 6, 7, 14, 42, 28, 812, DateTimeKind.Utc).AddTicks(4492),
                            Deadline = new DateTime(2022, 6, 16, 7, 6, 10, 225, DateTimeKind.Utc).AddTicks(5510),
                            Description = "Vero aliquam veniam qui. Aut facilis deleniti. Quae animi ut maxime adipisci et maiores amet neque fugiat. Voluptatem aut enim cum consequatur. Et doloremque optio reprehenderit ex.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1561840638",
                            Status = 1,
                            Title = "Nobis voluptatum natus."
                        },
                        new
                        {
                            Id = 64,
                            Address = "Sebastiangata 49, Lillestrand, Bermuda",
                            AuthorId = 1,
                            CompanyId = 51,
                            CreatedAt = new DateTime(2022, 6, 7, 17, 19, 47, 920, DateTimeKind.Utc).AddTicks(5349),
                            Deadline = new DateTime(2022, 6, 12, 18, 29, 26, 729, DateTimeKind.Utc).AddTicks(5906),
                            Description = "Ab ex rem praesentium. Eos officiis in et. Soluta qui et molestiae eius sunt sed ipsa praesentium. Aut odit fugiat aut ut eveniet enim magnam praesentium. Aperiam qui veritatis aut. Quaerat fuga atque quis qui enim voluptas.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=378355096",
                            Status = 1,
                            Title = "Assumenda sapiente et."
                        },
                        new
                        {
                            Id = 65,
                            Address = "Bakkes Vei 9, Vestbø, Costa Rica",
                            AuthorId = 1,
                            CompanyId = 55,
                            CreatedAt = new DateTime(2022, 6, 7, 20, 59, 48, 267, DateTimeKind.Utc).AddTicks(996),
                            Deadline = new DateTime(2022, 6, 8, 18, 33, 22, 390, DateTimeKind.Utc).AddTicks(5995),
                            Description = "Inventore recusandae placeat sequi facere dicta aperiam omnis est non. Fugit rem voluptatem magnam ipsam exercitationem qui nihil dignissimos adipisci. Voluptatem libero dolores est. Adipisci reprehenderit ratione. Laborum fugit dolorem expedita reiciendis aliquid enim deleniti.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1048159024",
                            Status = 1,
                            Title = "Quisquam veritatis dolores."
                        },
                        new
                        {
                            Id = 66,
                            Address = "Damskrenten 52, Sandøy, Lao People's Democratic Republic",
                            AuthorId = 1,
                            CompanyId = 46,
                            CreatedAt = new DateTime(2022, 6, 7, 15, 58, 32, 569, DateTimeKind.Utc).AddTicks(3210),
                            Deadline = new DateTime(2022, 6, 8, 11, 0, 12, 707, DateTimeKind.Utc).AddTicks(8034),
                            Description = "In eum deserunt in at. Rerum ut ducimus distinctio nesciunt qui saepe est iure. Aut perspiciatis quis fuga velit impedit et qui modi eum. Sed incidunt voluptas vero quisquam asperiores eveniet est quia aspernatur. Enim incidunt assumenda totam quam. Dolor exercitationem saepe.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=978747265",
                            Status = 1,
                            Title = "Quaerat quidem et."
                        },
                        new
                        {
                            Id = 67,
                            Address = "Haukelidsætersgate 18, Nærø, Turkmenistan",
                            AuthorId = 1,
                            CompanyId = 56,
                            CreatedAt = new DateTime(2022, 6, 7, 23, 48, 42, 911, DateTimeKind.Utc).AddTicks(2386),
                            Deadline = new DateTime(2022, 6, 8, 23, 5, 8, 128, DateTimeKind.Utc).AddTicks(681),
                            Description = "Voluptatem magnam eligendi eos vel beatae harum voluptatibus dolores. Tenetur quia sit laborum est laboriosam non porro voluptas architecto. Exercitationem labore ex et et et. Excepturi ea maxime excepturi sit. Quia ratione id molestias unde.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1834166695",
                            Status = 1,
                            Title = "Sit ut voluptatem."
                        },
                        new
                        {
                            Id = 68,
                            Address = "Fredriks Gate 9, Innodden, Mexico",
                            AuthorId = 1,
                            CompanyId = 55,
                            CreatedAt = new DateTime(2022, 6, 7, 15, 17, 24, 411, DateTimeKind.Utc).AddTicks(1496),
                            Deadline = new DateTime(2022, 6, 9, 0, 35, 36, 766, DateTimeKind.Utc).AddTicks(1767),
                            Description = "Voluptatem dignissimos quidem iure et. Quia aliquam delectus qui officiis sapiente. Qui et nam est magni cupiditate nesciunt. Cupiditate quo eum quasi sed. Laborum quia non quo harum corrupti similique.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1594499946",
                            Status = 1,
                            Title = "Et occaecati et."
                        },
                        new
                        {
                            Id = 69,
                            Address = "Malmekra 15, Gjessjøen, Benin",
                            AuthorId = 1,
                            CompanyId = 57,
                            CreatedAt = new DateTime(2022, 6, 7, 23, 3, 23, 4, DateTimeKind.Utc).AddTicks(8053),
                            Deadline = new DateTime(2022, 6, 13, 17, 11, 6, 448, DateTimeKind.Utc).AddTicks(3084),
                            Description = "Dolor voluptas et repudiandae fugiat aperiam voluptas. Sit alias qui. Rerum amet officia. Sint fuga voluptatem iste autem cupiditate et optio ut odit. Veritatis et accusamus.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1611050800",
                            Status = 1,
                            Title = "Suscipit sed accusamus."
                        },
                        new
                        {
                            Id = 70,
                            Address = "Kristians Vei 86, Nærmark, Wallis and Futuna",
                            AuthorId = 1,
                            CompanyId = 47,
                            CreatedAt = new DateTime(2022, 6, 8, 2, 33, 10, 397, DateTimeKind.Utc).AddTicks(3524),
                            Deadline = new DateTime(2022, 6, 9, 3, 10, 13, 844, DateTimeKind.Utc).AddTicks(6967),
                            Description = "Delectus et ab. Ipsum itaque beatae perferendis reiciendis libero quia voluptates. Et et reprehenderit ab consequatur iusto deleniti veniam. Eligendi eos soluta aut sint dolores omnis aperiam est. Maiores consequatur non reprehenderit beatae et ipsa nemo ipsam aut.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=336513893",
                            Status = 1,
                            Title = "Eos velit consequatur."
                        },
                        new
                        {
                            Id = 71,
                            Address = "Rognekroken 4, Fetfjell, Singapore",
                            AuthorId = 1,
                            CompanyId = 48,
                            CreatedAt = new DateTime(2022, 6, 8, 5, 51, 17, 362, DateTimeKind.Utc).AddTicks(513),
                            Deadline = new DateTime(2022, 6, 9, 22, 24, 31, 976, DateTimeKind.Utc).AddTicks(9559),
                            Description = "In mollitia adipisci provident. Nihil praesentium quam numquam sed possimus et consectetur. Sint nobis soluta. Porro eaque dolorem quisquam ab sed incidunt. Eos qui veritatis eveniet occaecati vel inventore.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1032355558",
                            Status = 1,
                            Title = "Et voluptate est."
                        },
                        new
                        {
                            Id = 72,
                            Address = "Johansensvei 28, Malborg, Colombia",
                            AuthorId = 1,
                            CompanyId = 50,
                            CreatedAt = new DateTime(2022, 6, 8, 5, 20, 16, 146, DateTimeKind.Utc).AddTicks(3177),
                            Deadline = new DateTime(2022, 6, 10, 22, 51, 21, 708, DateTimeKind.Utc).AddTicks(4706),
                            Description = "Vel cupiditate quod non hic provident quia rerum. Non sapiente quia possimus. Et perspiciatis cum molestias animi molestiae.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=608813333",
                            Status = 1,
                            Title = "Aliquid accusantium rerum."
                        },
                        new
                        {
                            Id = 73,
                            Address = "Søndre Brugrenda 6, Tandnes, Finland",
                            AuthorId = 1,
                            CompanyId = 60,
                            CreatedAt = new DateTime(2022, 6, 7, 20, 56, 19, 923, DateTimeKind.Utc).AddTicks(8753),
                            Deadline = new DateTime(2022, 6, 8, 12, 43, 43, 856, DateTimeKind.Utc).AddTicks(2521),
                            Description = "Et dolores at saepe architecto qui quas animi. Sit quasi dolore ullam voluptatem. Qui quae molestias reprehenderit occaecati autem rerum qui molestiae. Fugiat velit dolorem architecto.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1077980646",
                            Status = 1,
                            Title = "Occaecati est eius."
                        },
                        new
                        {
                            Id = 74,
                            Address = "Veggeveien 4, Lilledal, Norfolk Island",
                            AuthorId = 1,
                            CompanyId = 55,
                            CreatedAt = new DateTime(2022, 6, 8, 3, 46, 39, 536, DateTimeKind.Utc).AddTicks(318),
                            Deadline = new DateTime(2022, 6, 10, 0, 43, 9, 228, DateTimeKind.Utc).AddTicks(9894),
                            Description = "Nam fugiat nihil totam qui et. Dolorem nobis nisi quia et beatae sint. Est ut quaerat quo. Repellat nesciunt vitae et. Sint atque quis sit cumque culpa.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1327433230",
                            Status = 1,
                            Title = "Assumenda eum quidem."
                        },
                        new
                        {
                            Id = 75,
                            Address = "Thomassgate 7, Malstad, Anguilla",
                            AuthorId = 1,
                            CompanyId = 48,
                            CreatedAt = new DateTime(2022, 6, 7, 11, 5, 10, 304, DateTimeKind.Utc).AddTicks(8379),
                            Deadline = new DateTime(2022, 6, 8, 11, 0, 12, 708, DateTimeKind.Utc).AddTicks(644),
                            Description = "Quo dolor voluptatem iure dolore sit quia. Nisi doloremque nemo perferendis. Et eum et velit vero numquam consequatur. Et ab maiores vel.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=652678265",
                            Status = 1,
                            Title = "Aut qui accusantium."
                        },
                        new
                        {
                            Id = 76,
                            Address = "Eriksens Vei 6, Høystrand, Falkland Islands (Malvinas)",
                            AuthorId = 1,
                            CompanyId = 47,
                            CreatedAt = new DateTime(2022, 6, 8, 6, 3, 33, 602, DateTimeKind.Utc).AddTicks(7002),
                            Deadline = new DateTime(2022, 6, 9, 6, 7, 28, 455, DateTimeKind.Utc).AddTicks(5865),
                            Description = "Rem eos eum doloremque libero et. Eos alias aut tenetur dolore dolorem quisquam iure aliquam atque. Dignissimos voluptas quia architecto et placeat. Aut voluptatem non.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1275511885",
                            Status = 1,
                            Title = "Quidem et voluptatem."
                        },
                        new
                        {
                            Id = 77,
                            Address = "Sebastians Gate 2, Sandstrøm, Liberia",
                            AuthorId = 1,
                            CompanyId = 52,
                            CreatedAt = new DateTime(2022, 6, 7, 12, 53, 40, 992, DateTimeKind.Utc).AddTicks(6583),
                            Deadline = new DateTime(2022, 6, 9, 12, 33, 4, 503, DateTimeKind.Utc).AddTicks(6598),
                            Description = "Nihil voluptatibus voluptas et illum nostrum qui aut alias. Ea cum quod dolor inventore quae non ex. Velit rerum quos vel autem recusandae non totam. Rerum similique eos. Tempora neque et tempora quaerat est dolore.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=152777975",
                            Status = 1,
                            Title = "Pariatur quia sequi."
                        },
                        new
                        {
                            Id = 78,
                            Address = "Fossehaugen 94, Loberg, Western Sahara",
                            AuthorId = 1,
                            CompanyId = 55,
                            CreatedAt = new DateTime(2022, 6, 7, 11, 43, 43, 369, DateTimeKind.Utc).AddTicks(3467),
                            Deadline = new DateTime(2022, 6, 14, 16, 21, 32, 951, DateTimeKind.Utc).AddTicks(6557),
                            Description = "Autem temporibus et. Maxime labore placeat. Unde eaque recusandae et sit. Aspernatur reiciendis eveniet itaque doloribus voluptate.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=345886486",
                            Status = 1,
                            Title = "In nam natus."
                        },
                        new
                        {
                            Id = 79,
                            Address = "Moes Vei 0, Storhelle, Lithuania",
                            AuthorId = 1,
                            CompanyId = 55,
                            CreatedAt = new DateTime(2022, 6, 8, 5, 46, 26, 137, DateTimeKind.Utc).AddTicks(3442),
                            Deadline = new DateTime(2022, 6, 11, 7, 32, 21, 367, DateTimeKind.Utc).AddTicks(3412),
                            Description = "Quisquam blanditiis et fugiat quaerat. Quo inventore aut. Dolorum quasi illo pariatur ea voluptates.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=636024233",
                            Status = 1,
                            Title = "A est iste."
                        },
                        new
                        {
                            Id = 80,
                            Address = "Fridasgate 54, Tandfjell, Indonesia",
                            AuthorId = 1,
                            CompanyId = 53,
                            CreatedAt = new DateTime(2022, 6, 7, 12, 16, 49, 195, DateTimeKind.Utc).AddTicks(6743),
                            Deadline = new DateTime(2022, 6, 13, 4, 10, 8, 645, DateTimeKind.Utc).AddTicks(2293),
                            Description = "Laudantium provident doloremque non sunt voluptatem quia veniam. Corrupti distinctio dolor quis molestiae autem facere ipsum reiciendis iste. Vel qui id quo. Eius suscipit et omnis quibusdam quibusdam reiciendis. Et debitis sunt dolorum similique aut reiciendis. Natus eos nemo.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=138230806",
                            Status = 1,
                            Title = "Ut vel quisquam."
                        },
                        new
                        {
                            Id = 81,
                            Address = "Andersensgate 5, Lillevik, Germany",
                            AuthorId = 1,
                            CompanyId = 48,
                            CreatedAt = new DateTime(2022, 6, 7, 21, 47, 54, 414, DateTimeKind.Utc).AddTicks(9375),
                            Deadline = new DateTime(2022, 6, 10, 15, 54, 13, 229, DateTimeKind.Utc).AddTicks(9662),
                            Description = "Est tempore inventore accusamus autem dolorem eos et quam. Quia eum similique porro quo. Consequatur nobis totam sint et saepe dolores sapiente quasi enim. Aut illum ullam est eligendi et. Aut fugiat illo dolorum.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1150322860",
                            Status = 1,
                            Title = "Ut blanditiis autem."
                        },
                        new
                        {
                            Id = 82,
                            Address = "Østre Brugjerdet 3, Lomark, Angola",
                            AuthorId = 1,
                            CompanyId = 52,
                            CreatedAt = new DateTime(2022, 6, 7, 23, 12, 39, 330, DateTimeKind.Utc).AddTicks(2368),
                            Deadline = new DateTime(2022, 6, 8, 16, 52, 38, 767, DateTimeKind.Utc).AddTicks(9067),
                            Description = "Cum perspiciatis id est veniam odio sunt soluta laboriosam. Illo maiores excepturi pariatur ut sed. Consequatur voluptatem ea est pariatur molestiae nulla aut. Beatae in aut. Et consequatur laborum. Vero repellat nihil impedit aut fugit ut.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=941861862",
                            Status = 1,
                            Title = "Porro odit iure."
                        },
                        new
                        {
                            Id = 83,
                            Address = "Granengen 7, Malodden, Austria",
                            AuthorId = 1,
                            CompanyId = 47,
                            CreatedAt = new DateTime(2022, 6, 8, 9, 16, 48, 136, DateTimeKind.Utc).AddTicks(3701),
                            Deadline = new DateTime(2022, 6, 12, 16, 32, 47, 794, DateTimeKind.Utc).AddTicks(8800),
                            Description = "Iste dicta dolores ducimus. Saepe enim et. Est consequatur totam dolorem voluptatem ut beatae cupiditate nam. Voluptatibus aut magni sunt sint qui pariatur aut. Minus id voluptatem at qui ut quaerat illo totam.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=512888137",
                            Status = 1,
                            Title = "Quae enim earum."
                        },
                        new
                        {
                            Id = 84,
                            Address = "Sondreveien 77, Lilleberg, Hong Kong",
                            AuthorId = 1,
                            CompanyId = 46,
                            CreatedAt = new DateTime(2022, 6, 7, 20, 9, 4, 378, DateTimeKind.Utc).AddTicks(8809),
                            Deadline = new DateTime(2022, 6, 10, 1, 25, 5, 829, DateTimeKind.Utc).AddTicks(4590),
                            Description = "Qui quisquam doloremque et velit dolor. Inventore et nostrum et placeat sit fugit laudantium tempore quia. Omnis sunt illo qui. Quasi fugit provident et ea aperiam. Dicta quidem inventore quae deserunt debitis nam. Error et rerum aliquam.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1661337351",
                            Status = 1,
                            Title = "Voluptate molestiae quia."
                        },
                        new
                        {
                            Id = 85,
                            Address = "Tingtunet 37, Nordfjord, Bangladesh",
                            AuthorId = 1,
                            CompanyId = 54,
                            CreatedAt = new DateTime(2022, 6, 8, 8, 53, 43, 820, DateTimeKind.Utc).AddTicks(9113),
                            Deadline = new DateTime(2022, 6, 20, 7, 47, 35, 749, DateTimeKind.Utc).AddTicks(1305),
                            Description = "Iusto in laboriosam aut et ea sint. Aliquid molestias illo. Qui quae magni. Explicabo aliquam et. Nostrum ut soluta recusandae sint. Minima eum iusto sunt dolores veritatis perferendis quia vel dolore.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1865509517",
                            Status = 1,
                            Title = "Ipsam voluptatem et."
                        },
                        new
                        {
                            Id = 86,
                            Address = "Maries Vei 25, Nærstrand, Bahrain",
                            AuthorId = 1,
                            CompanyId = 49,
                            CreatedAt = new DateTime(2022, 6, 8, 10, 57, 3, 936, DateTimeKind.Utc).AddTicks(3710),
                            Deadline = new DateTime(2022, 6, 11, 20, 53, 20, 511, DateTimeKind.Utc).AddTicks(8807),
                            Description = "Earum laborum facere recusandae. Sapiente illum est voluptas ut perspiciatis. In delectus quia perferendis aperiam. Nisi architecto odio rerum ex beatae magni dolore quia. Et et quia eos libero possimus corporis incidunt nulla.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=476679648",
                            Status = 1,
                            Title = "Voluptatem sint iste."
                        },
                        new
                        {
                            Id = 87,
                            Address = "Øvre Malmmoen 4, Stavborg, Uganda",
                            AuthorId = 1,
                            CompanyId = 55,
                            CreatedAt = new DateTime(2022, 6, 7, 21, 16, 59, 913, DateTimeKind.Utc).AddTicks(230),
                            Deadline = new DateTime(2022, 6, 9, 6, 38, 0, 718, DateTimeKind.Utc).AddTicks(7793),
                            Description = "Animi reiciendis voluptatum pariatur eum consequuntur labore doloribus. Vero at adipisci. Culpa libero ut rem vel molestias et molestiae exercitationem quo. Ad minus quia ad quo aspernatur enim. Est sed quaerat veritatis ea. Omnis dolorem est quos voluptatem facilis voluptates.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1556424747",
                            Status = 1,
                            Title = "Molestiae sed rem."
                        },
                        new
                        {
                            Id = 88,
                            Address = "Malingata 8, Sandby, San Marino",
                            AuthorId = 1,
                            CompanyId = 52,
                            CreatedAt = new DateTime(2022, 6, 7, 19, 39, 59, 215, DateTimeKind.Utc).AddTicks(4658),
                            Deadline = new DateTime(2022, 6, 13, 14, 11, 27, 17, DateTimeKind.Utc).AddTicks(342),
                            Description = "Voluptatem velit fugiat odit magnam. Et quis quia placeat ipsam ipsa. Fugiat est rem quia incidunt ut accusantium. Omnis eveniet voluptatem ut nam laboriosam commodi laudantium.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1012145067",
                            Status = 1,
                            Title = "Quia autem aut."
                        },
                        new
                        {
                            Id = 89,
                            Address = "Karolinesvei 46, Stavstrøm, Senegal",
                            AuthorId = 1,
                            CompanyId = 46,
                            CreatedAt = new DateTime(2022, 6, 7, 21, 14, 33, 810, DateTimeKind.Utc).AddTicks(7015),
                            Deadline = new DateTime(2022, 6, 8, 14, 4, 40, 309, DateTimeKind.Utc).AddTicks(1528),
                            Description = "Illum quam incidunt et reprehenderit rerum et illo tempore. Earum dolor non animi. Accusantium vel deserunt nihil doloribus mollitia nobis sit debitis error. Aliquid nihil sequi ad quis. Minima aut eum omnis esse quis neque qui iste quia. Aliquid inventore distinctio voluptates alias eum est ea nobis voluptates.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=693895452",
                            Status = 1,
                            Title = "Sunt ea molestiae."
                        },
                        new
                        {
                            Id = 90,
                            Address = "Solbergveien 42, Gjesfjell, Cyprus",
                            AuthorId = 1,
                            CompanyId = 55,
                            CreatedAt = new DateTime(2022, 6, 7, 20, 20, 9, 327, DateTimeKind.Utc).AddTicks(5669),
                            Deadline = new DateTime(2022, 6, 11, 2, 51, 10, 297, DateTimeKind.Utc).AddTicks(3957),
                            Description = "Porro eum blanditiis autem. Alias nam laboriosam in nesciunt sint dolores. Sit hic rerum quia iure non sequi. Dolores eum velit ipsum vel vel eius voluptatum laborum. Numquam corporis veritatis ut.",
                            PostingUrl = "https://loremflickr.com/320/240?lock=1587278912",
                            Status = 1,
                            Title = "Rerum quia in."
                        });
                });

            modelBuilder.Entity("Celestia.Models.Company", b =>
                {
                    b.HasOne("Celestia.Models.Account", "Author")
                        .WithMany("Companies")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_companies_accounts_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Celestia.Models.Contact", b =>
                {
                    b.HasOne("Celestia.Models.Account", "Author")
                        .WithMany("Contacts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contacts_accounts_author_id");

                    b.HasOne("Celestia.Models.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("fk_contacts_companies_company_id");

                    b.Navigation("Author");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Celestia.Models.Folder", b =>
                {
                    b.HasOne("Celestia.Models.Account", "Author")
                        .WithMany("Folders")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_folders_accounts_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Celestia.Models.Job", b =>
                {
                    b.HasOne("Celestia.Models.Account", "Author")
                        .WithMany("Jobs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_accounts_author_id");

                    b.HasOne("Celestia.Models.Company", "Company")
                        .WithMany("Job")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("fk_jobs_companies_company_id");

                    b.HasOne("Celestia.Models.Folder", "Folder")
                        .WithMany("Jobs")
                        .HasForeignKey("FolderId")
                        .HasConstraintName("fk_jobs_folders_folder_id");

                    b.Navigation("Author");

                    b.Navigation("Company");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Celestia.Models.Account", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Contacts");

                    b.Navigation("Folders");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Celestia.Models.Company", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Celestia.Models.Folder", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
